version: '3.9'
services:
  glances:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    pid: "host"
    privileged: true
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"
    environment:
      - TZ=${TZ}
      - GLANCES_OPT=-C /glances/conf/glances.conf -w
#     # Uncomment for GPU compatibility (Nvidia) inside the container
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities: [gpu]
#     # Uncomment to protect Glances WebUI by a login/password (add --password to GLANCES_OPT)
#     secrets:
#       - source: glances_password
#         target: /root/.config/glances/<login>.pwd

# secrets:
#   glances_password:
#     file: ./secrets/glances_password
